// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCzPhIweeqRzmMK7KKArEXHlywvkKTBH8',
    appId: '1:702938202731:web:1a9f9471bc5a39773aa72e',
    messagingSenderId: '702938202731',
    projectId: 'bakky-658b0',
    authDomain: 'bakky-658b0.firebaseapp.com',
    databaseURL: 'https://bakky-658b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bakky-658b0.appspot.com',
    measurementId: 'G-5H5V12PEHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEaPWmC8GtuCATCFcy2JQKFjHvAxAnAUc',
    appId: '1:702938202731:android:0365ec6da18e59dd3aa72e',
    messagingSenderId: '702938202731',
    projectId: 'bakky-658b0',
    databaseURL: 'https://bakky-658b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bakky-658b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP8dC4Itx1F_8fTIIi4zJk2-Xig2RfMWg',
    appId: '1:702938202731:ios:f9bc77a51d8416e43aa72e',
    messagingSenderId: '702938202731',
    projectId: 'bakky-658b0',
    databaseURL: 'https://bakky-658b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bakky-658b0.appspot.com',
    iosBundleId: 'com.example.bakenda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP8dC4Itx1F_8fTIIi4zJk2-Xig2RfMWg',
    appId: '1:702938202731:ios:94baac54e4e6fff53aa72e',
    messagingSenderId: '702938202731',
    projectId: 'bakky-658b0',
    databaseURL: 'https://bakky-658b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bakky-658b0.appspot.com',
    iosBundleId: 'com.example.bakenda.RunnerTests',
  );
}
